---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "(/{locale)}/v1/users/login":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    post:
      summary: login user
      responses:
        '200':
          description: successful
  "(/{locale)}/v1/users":
    parameters:
    - name: locale
      in: path
      description: locale
      required: true
      schema:
        type: string
    post:
      summary: create user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
